[tool.poetry]
name = "afoley-site"
version = "0.1.0"
description = ""
authors = ["Alexander Foley <alexandergfoley@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
ansible = "2.9.14"
jinja2 = "^2.11.2"
pyyaml = "^5.3.1"
docker = "^4.2.2"
cryptography = "^2.9.2"
ansible-lint = "^4.2.0"
docker-compose = "^1.26.2"
python-markdown-math = "^0.7"
WeasyPrint = "^51"
jmespath = "^0.10.0"
jsondiff = "^1.2.0"
pygments = "^2.6.1"
mkdocs = "^1.1.2"
mkdocs-git-revision-date-localized-plugin = "^0.7"
mkdocs-material = "6.1.0"
mkdocs-material-extensions = "^1.0"
mkdocs-monorepo-plugin = "^0.4.9"
mkdocs-minify-plugin = "^0.3.0"
mkdocs-macros-plugin = "^0.4.9"
mkdocs-mermaid2-plugin = "^0.5.1"
awscli = "^1.18.122"
requests = "^2.24.0"
boto = "^2.49.0"
boto3 = "^1.14.46"
python-dateutil = "^2.8.1"
hvac = "^0.10.5"
passlib = "^1.7.2"
mkdocs-git-revision-date-plugin = "^0.3.1"
mkdocs-simple-plugin = "^0.1.8"
diagrams = "^0.17.0"
pylint = "^2.6.0"
openshift = "0.11.2"
packaging = "20.8"
mkdocs-windmill-dark = "0.2.0"
mkdocs-bootstrap4 = "0.1.5"
pylab-sdk = "1.3.2"
audiosegment = "0.23.0"
librosa = "0.8.1"
mkdocs-gitbook = "0.0.1"
imutils = "0.5.4"
opencv-python = "4.5.3.56"
imageio = "2.9.0"
<<<<<<< HEAD
SpeechRecognition = "3.8.1"
PyAudio = "0.2.11"
pyttsx3 = "2.90"
newsapi-python = "0.2.6"
random-word = "1.0.4"
# ibm_watson = ""
# ibm_cloud_sdk_core = ""
=======
>>>>>>> parent of 47f5e58 (feat: Adding the jarvis stuff / good news bot / IBM and google SR)

[tool.poetry.dev-dependencies]
pylint = "^2.6.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
