---
site_name: "Alex Foley"
site_description: "Alex Foley Info."
site_author: "alex foley"
site_url: "https://alexfoley.info"

copyright: "&copy; 2021 Alex Foley"

repo_name: ""
repo_url: ""

docs_dir: "static"

theme: 
    name: windmill-dark
    features:
        - navigation.tabs



markdown_extensions:
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
        options: 
            attributes:
                height: 1px
                width: 1px
    - attr_list
    - toc:
        permalink: true
        separator: "-"


plugins:
    - search:
        separator: '[\s\-\.]+'
        lang:
            - en
    - monorepo
extra_css:
    - "assets/css/custom.css"
extra:
    social:
        - icon: "fontawesome/brands/github"
          link: "https://github.com/afoley587"

nav:
    - "Home": "index.md"
    - "About":
        # Temp fix for cloudfront
        # https://aws.amazon.com/blogs/compute/implementing-default-directory-indexes-in-amazon-s3-backed-amazon-cloudfront-origins-using-lambdaedge/
        - "Experience": "about/experience/index.html"
        - "Hobbies": "about/hobbies/index.html"
    - "Portfolio": "https://dash.engineeringwithalex.io"
    - "Blog": "https://blog.engineeringwithalex.io"